### ISSUE TITLE
update pathway group cv term dependants

### ISSUE THREAD

**Issue by hattrill** [FlyBase/GO-curation#110]
For next Fbcv update:

Ask Harvard and IU to update: 'signaling pathway group' instead of pathway group

Impacts: 
web: pathway pages, search tab
IU: pathway file and markdown list

**Comment by hattrill** [comment]
New term for FBcv:0007034 ; signaling pathway group will be in for FB2024_03 EP4

- [x] Proforma to update signaling pathway groups cv term
- [x] Web ticket for group
- [x] IU ticket for markdown and pathway file

**Comment by hattrill** [comment]
replace: pathway group  -> signaling pathway group 
for 72 gene groups

(note: pathway group ; FBCV:0003017)

**Comment by hattrill** [comment]
Hi @gantonazzo - are you still making the file for the pathway networks? 
If so, I have changed all pathway groups cv to:
FBcv:0007034
signaling pathway group
Should be 72 instances.
I will add to HarvDev ticket for Chris' attention as well.

**Comment by gantonazzo** [comment]
> Hi @gantonazzo - are you still making the file for the pathway networks? If so, I have changed all pathway groups cv to: FBcv:0007034 signaling pathway group Should be 72 instances. I will add to HarvDev ticket for Chris' attention as well.

Yes, I will still make the files for this release and, if Chris can match my output files, then he will take over from the following release. I warned him that we would have to change the CV term in these release, but I still have to tweak the scripts so he can do the same on his side.

**Comment by hattrill** [comment]
I am going to close this as tickets are on jira now.
