### ISSUE TITLE
Finish enrichment tool work

### ISSUE THREAD

**Issue by hattrill** [FlyBase/GO-curation#32]
Work to finish off enrichment tool work:
1. Update slims 
2. Check about  DB updates
3. Make sure that the tool is finished - test with datasets and review requested improvements
4. Link from FB - export from hitlist?

**Comment by gantonazzo** [comment]
See https://github.com/FlyBase/GO-curation/issues/37 for updated list of tasks

**Comment by hattrill** [comment]
Closing this as #37 should be used for remaining tasks
