### ISSUE TITLE
STING signaling

### ISSUE THREAD

**Issue by hattrill** [FlyBase/GO-curation#36]
STING anit-viral response needs some work in the GO to capture properly. Discuss with Sylvian, as he has done extensive review on this and BP terms have issues with the GOC
go-ontology/issues/21980

PMID:30119996
PMID:29924997

**Comment by hattrill** [comment]
Looks like new term created as part of go-ontology/issues/17080; added 2022-07-26

**Comment by hattrill** [comment]
- [x] Make Pathway group
- [x] New diagram
- [x] GO review

**Comment by hattrill** [comment]
Will have to co-annotate with specific innate response to terms e.g. GO:0140374 antiviral innate immune response
as [GO:0140896](https://www.ebi.ac.uk/QuickGO/term/GO:0140896) cGAS/STING signaling pathway child of innate immune repsonse (as can be activated by other pathogens).
![Screenshot 2022-09-01 at 16 53 50](https://user-images.githubusercontent.com/11865746/187959268-13514c0e-4ba3-4b59-95b2-30af66ae84c3.png)

**Comment by hattrill** [comment]
New Term requested for cyclic diGMP transport: go-ontology/issues/24013

**Comment by hattrill** [comment]
Hey @gantonazzo - could you have a quick look at this paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8771144/

Do you think that CNT2 could be given positive reg of cGAS-STING pathway. I think it's more of a causally upstream, but technically it's acting at a point after the beginning of the pathway. Not sure if we've come across anything similar before.

**Comment by gantonazzo** [comment]
Hi Helen, 

It's tricky. Normally I don't think I would consider it as a positive regulator, but it's also true that it's not upstream of the whole pathway, it's just upstream of part of the pathway.

If we consider the current definition, and we still want to capture the role of CNT2 for oral CDN protection, maybe we could give it a positive regulation term for now. I don't think it's correct, but it's also technically wrong to say CNT2 is upstream of the whole pathway. Is there a plan to make more terms for this signalling?

(note: I've changed my mind multiple times on the issue while writing this, so I may have a different opinion on this tomorrow!:D)

**Comment by hattrill** [comment]
Glad that I am not the only one feeling a bit giddy about this one. At the moment, this term doesn't even have a regulation branch. I am going to think about it some more.....I feel that this channel is a bit 'passive' and so isn't what I would think of regulatory.

I think that I might give this acts_upstream_of_positive_effect "cyclic-nucleotide-mediated signaling" as I think that's more accurate.

**Comment by gantonazzo** [comment]
Sounds like a good plan!

**Comment by hattrill** [comment]
Requested reg terms for pathway: geneontology/go-ontology/issues/24016
Don't have any dmel papers to annotate with reg terms yet, but PMID:29875158 https://pubmed.ncbi.nlm.nih.gov/29875158/ shows that Bombyx mori Casp8L can negatively regulate the cGAS/STING signaling pathway

**Comment by hattrill** [comment]
+[Term]
+id: GO:0140927
+name: cyclic-di-GMP transmembrane transporter activity
+namespace: molecular_function
+def: "Enables the transfer of cyclic-di-GMP from one side of a membrane to the other." [PMID:34965418]
+intersection_of: GO:0022857 ! transmembrane transporter activity
+intersection_of: has_primary_input CHEBI:58805 ! c-di-GMP(2-)
+created_by: pg
+creation_date: 2022-10-18T13:17:30Z
