### ISSUE TITLE
Update Toll signalling annotations

### ISSUE THREAD

**Issue by hattrill** [FlyBase/GO-curation#41]
We now have the terms:
GO:0160032	Toll receptor ligand protein activation cascade
GO:0160034	positive regulation of Toll receptor ligand protein activation cascade
GO:0160035	negative regulation of Toll receptor ligand protein activation cascade

- [x] Replace annotations to members of

[Extracellular Spatzle Activating Pathway Core Components](http://flybase.org/reports/FBgg0001056.html)
and 
[Negative Regulators of Spatzle Activating Pathway](http://flybase.org/reports/FBgg0001055.html)

- [x] Replace terms on pathway pages after FB_2022_05 GO cv update.

**Comment by gantonazzo** [comment]
Since the terms are already available in P2GO, should I proceed with this retrofit, so it's off our list, or did you want to fix the grouping/go terms on the pathway pages first?

**Comment by hattrill** [comment]
No - please go ahead and update the annotations! That would be great.
I will fix the pathway pages after the GO update.

**Comment by gantonazzo** [comment]
Ok, this is done, I just have to dispute a few annotations made by Swiss-Prot via PMID:18724373 and PMID:26843333 that still use regulation terms instead of the new terms.

**Comment by hattrill** [comment]
Make record for GO cv update: ha0225556 for FB_2022_05_EP7

**Comment by gantonazzo** [comment]
> Ok, this is done, I just have to dispute a few annotations made by Swiss-Prot via PMID:18724373 and PMID:26843333 that still use regulation terms instead of the new terms.

Update: now all the disputed annotations have been fixed as well

**Comment by hattrill** [comment]
Chrcked gene_group report.
*a TL-SPZC
*z FBgg0001056
*e Extracellular Spatzle Activating Pathway Core Components
*d Toll receptor ligand protein activation cascade ; GO:0160032

*a TL-SPZN
*z FBgg0001055
*e Negative Regulators of Spatzle Activating Pathway
*d negative regulation of Toll receptor ligand protein activation cascade ; GO:0160035

Think that we can close this now.
