### ISSUE TITLE
Pathway networks

### ISSUE THREAD

**Issue by hattrill** [FlyBase/GO-curation#50]
Hi Giulia,

Just a thought....

Could you investigate whether we could have a version of networks where un-connected nodes are displayed?

**Comment by gantonazzo** [comment]
Hi Helen,

I think it should be doable. We can for sure display the self-interacting nodes (i.e. those that only interact with themselves), but I think we should be able to show the non-interacting ones as well. Would you like the self-interacting nodes to be displayed as self-interactions, or would you prefer to just have those nodes floating around with no interaction at all?

**Comment by hattrill** [comment]
I think best to hide self-interactions and only show floating friends.

**Comment by hattrill** [comment]
Giulia has made examples using EGFR as has quite a lo of unconnected nodes. Attaching output:
<img width="839" alt="egfr_func" src="https://user-images.githubusercontent.com/11865746/198216866-b771ce9e-339b-4023-a89a-93b29d4afe84.png">
<img width="825" alt="egfr_reg" src="https://user-images.githubusercontent.com/11865746/198216874-ec80593d-8543-4937-8e54-37e03a6d9134.png">

Should show these to group to decide whether to use these instead of just connected nodes.

**Comment by hattrill** [comment]
compare with current version only showing nodes with phys_int connections.
<img width="414" alt="Screenshot 2022-10-27 at 08 21 18" src="https://user-images.githubusercontent.com/11865746/198217563-0d07246d-9fa1-45fe-85ac-12b8d5e48fd4.png">
<img width="421" alt="Screenshot 2022-10-27 at 08 21 13" src="https://user-images.githubusercontent.com/11865746/198217577-36d1dce8-9ca3-44da-82b4-965698e9f09e.png">

**Comment by hattrill** [comment]
[Presentation to group 02112022](https://docs.google.com/presentation/d/1nbbNhL6sllni8QHAnBauEyHO0Mltjr_FkcrlZoA06U0/edit#slide=id.p)

Decided to show unconnected nodes and add note in release notes and see if anyone complains.
