### ISSUE TITLE
Test PANGEA 1.1 beta

### ISSUE THREAD

**Issue by hattrill** [FlyBase/GO-curation#59]
@gantonazzo I am just making a ticket to list the issues that we come across. Perhaps we can reciprocally test the bugs to see if we see them

https://www.flyrnai.org/tools/pangea/web/home/7227

**Comment by hattrill** [comment]
Issue List (edit to update): Adding significant issues to https://docs.google.com/spreadsheets/d/1CwWgdn4DZlNryiu8vzj0e6e6js3PWwUy2CXQ4Fm3roI/edit#gid=0

**INPUT** 
1. Export gene list from FB not working. Re-openned https://flybase.atlassian.net/browse/WEB-2028?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel **[FIXED]**

**GRAPH NETWORK**
1. Can't seem to generate a graph network  **[FIXED]**
2. edges need to be different colours to see overlaps
<img width="766" alt="Screenshot 2023-01-11 at 09 53 51" src="https://user-images.githubusercontent.com/11865746/211775528-75c75b1e-8651-4322-8d07-716879f22df5.png">
3. With large gene sets would be good if nodes were more seperate e.g. here the abnormal cell number hides the DO overlaps - can we use colour to help here?
<img width="495" alt="Screenshot 2023-02-01 at 18 07 23" src="https://user-images.githubusercontent.com/11865746/216126838-b986ba8d-df17-452d-821b-21fb2da09794.png">


4. The selection buttons aren't super-obvious as being alternative choices
<img width="210" alt="Screenshot 2023-02-01 at 17 53 43" src="https://user-images.githubusercontent.com/11865746/216124955-fce3000d-7367-4fce-a6b4-38d5bf839768.png">


**SETS**
1. Generic GO consortium Subsets (GO slim) looks like old FB SLIM1. Update with the GOC 
labelled as goslim_generic in go-basic.obo
2. Should we include the AGR and fly ribbon subsets? If we do want to have this limited set, should just use the AGR subset across the organsims for consistency.
3. Looks like only "hierarchy" set uses hierarchy. All except direct should use hierarchy - I think we should get rid off 'direct' as it's not correct to use it like this.
4. Slimming over **regulation** in BP would be a nice addition?  should we add this set?
6. Remove root terms from sets as either used with ND evidence code to show that nothing is known or, if using graph then everything in tht aspect will map up:
GO:0008150	biological_process
GO:0003674	molecular_function
GO:0005575	cellular_component
![Screenshot 2023-02-01 at 13 04 02](https://user-images.githubusercontent.com/11865746/216051709-0797a1d6-38dd-4b8d-b445-5afe542cc5a9.png)

7. COMPLEAT sets don't seem to make much sense: think that we should restict these to geniune complexes or interpretation will be confusing with other sets.
<img width="1320" alt="Screenshot 2023-01-11 at 20 31 41" src="https://user-images.githubusercontent.com/11865746/211911894-8683981b-3f01-4606-b227-7f6e6874aeb4.png">
8. Look at the way that the expression sets have been generated. Preferred tissue (modEncode RNA_seq) - I don't think that this works very well for enrichment - how can we improve this?
<img width="1245" alt="Screenshot 2023-01-11 at 20 52 08" src="https://user-images.githubusercontent.com/11865746/211915469-ef8d8184-888d-4bc3-9608-380a8f4806cf.png">

9. Expression annotation AGR - looks like just direct to terms - would be better if used ontology structure - perhaps we could use the AGR slim for this?


**BAR VISUALIZATION**
1. Can't see Menu ("Use the ... menu to download svg/pngs")
2. Would be nice to be able to select GO terms that seem interesting - can't even copy-paste them from axis
5. [set number] is next to GO name for every point on chart. There doesn't appear to be a way to map this to a set name.
<img width="207" alt="Screenshot 2023-01-11 at 10 14 52" src="https://user-images.githubusercontent.com/11865746/211779420-f4915e17-696f-449a-96e1-a98055d6e086.png">

**RESULTS TABLE**
1. Selecting sets for visualization is a bit clunky - have to use alt/shift to select multiple, when none are selected all are analysed. Could be better - select all as default; clear button, unselect by specifically clicking on box not clearing when clicking another
2. Table on first page and "Mapped Gene Graph Visualization " page should be the same
4. How can we show hierarchy of GO in results?
10. Show top 100 in list, as top 10 mis-leading

**DOC**
Some of FAQ and Genesets info should be together

**OTHER SPECIES ISSUES**

1. When on results page, click NEW SEARCH button goes back to drosophila pge https://www.flyrnai.org/tools/pangea/web/home/7227 [added issue to Testing sheet]
2. Worm example list and background are the same [added issue to Testing sheet]
3. Worm phenotype section contains expression  [added issue to Testing sheet]
<img width="182" alt="Screenshot 2023-02-01 at 18 50 54" src="https://user-images.githubusercontent.com/11865746/216136380-afa76ec1-d93d-4655-b7c8-617c290b5bbf.png">

4. . For Rat and Z. fish the test set when combined with an EBI CP enrichment brings up a query error [added issue to Testing sheet]
 
![Screenshot 2023-02-01 at 12 25 45](https://user-images.githubusercontent.com/11865746/216042871-299bd982-3beb-42d4-ae62-dd6f86040d9e.png)

**Other**
1. Could we open a new tab for other visualization pages - would be nice if we could keep the selection sets from the first page
2. Rename category **FlyBase phenotype for classical alleles** to **FlyBase Phenotype** (we can use doc to explain this as these are mainly classical and insertion alleles). [added issue to Testing sheet]
3. Rename any AGR refs to Alliance or they will be sad e.g.
**Disease annotation AGR** to **Alliance Disease annotation**
**Expression annotation AGR** to **Alliance Expression annotation**
4. Can't go back to query page with input - would be good as you could add more sets if you had another thought [FIXED]

TESTERS SHEET:
https://docs.google.com/spreadsheets/d/1CwWgdn4DZlNryiu8vzj0e6e6js3PWwUy2CXQ4Fm3roI/edit#gid=0

**Comment by hattrill** [comment]
Nice Examples for paper:
to show also non-overlapping set
<img width="774" alt="Screenshot 2023-01-11 at 14 28 44" src="https://user-images.githubusercontent.com/11865746/211832000-b2a386e5-3f48-4a2f-a494-14775c649636.png">

**Comment by hattrill** [comment]
Example of where groups overlap and don't 
<img width="817" alt="Screenshot 2023-01-11 at 14 43 11" src="https://user-images.githubusercontent.com/11865746/211835364-48d16a36-3ed3-4bc0-8d80-981fff44560e.png">

**Comment by hattrill** [comment]
Good example of how different BP and CCs group . With more colours, this would be clearer.

<img width="932" alt="Screenshot 2023-01-11 at 20 02 36" src="https://user-images.githubusercontent.com/11865746/211906527-1d0a7f4a-0380-4af8-ba8d-85dfc6977b48.png">

**Comment by hattrill** [comment]
TEST SETS
**FLY**
QuickSearch, pheno_anat fat body 
[fat_body_affected.txt](https://github.com/FlyBase/GO-curation/files/10395964/fat_body_affected.txt)

**WORM**
using phenotype ontology viewer for query:
List of 247 genes that were annotated with WBPhenotype:0000598 alimentary system morphology variant or any of its transitive descendant 
[genes_direct_and_inferred_for_WBPhenotype 0000598.txt](https://github.com/FlyBase/GO-curation/files/10555877/genes_direct_and_inferred_for_WBPhenotype.0000598.txt)

**Comment by hattrill** [comment]
For Worm BP using hier. showing overlap between 
endocytosis
digestive tract morphogenesis 
tube development 
![enrichment(1)](https://user-images.githubusercontent.com/11865746/216015777-d7cf1378-02eb-4c6b-acd4-0c05a440f49f.svg)

**Comment by hattrill** [comment]
Note about advantages: can use enrichment and classification on same sets

**Comment by hattrill** [comment]
Nice illustration of how certain diseases are associated with certain cell features/exp using http://preview.flybase.org/reports/FBgg0000056.html gene group.

![enrichment(8)](https://user-images.githubusercontent.com/11865746/216626417-b855c063-af78-4412-97a1-7e275656544d.svg)

and with even more anat/cc/disease
![enrichment(9)](https://user-images.githubusercontent.com/11865746/216627289-e078ca16-0806-42b4-9014-5b4c441fff8d.svg)

**Comment by gantonazzo** [comment]
Still a few issues remain when running a multiple search query:

**1)** When I run a multiple search I never get to the result page automatically, I always have to click on the “Results” button for redirection
<img width="387" alt="Screenshot 2023-02-08 at 15 05 25" src="https://user-images.githubusercontent.com/16778756/217568133-e017b059-10a4-4f20-a157-6d381adbf256.png">

**2)** Typo after submission: “Cacluation progress” instead of “Calculation progress” (see previous screenshot)

**3)** It seems when I select all rows to plot, no graph gets generated. It works as intended when you just select a subset of rows

**4)** overlapping labels in graph is still a issue (Gene 
<img width="604" alt="Screenshot 2023-02-08 at 15 04 07" src="https://user-images.githubusercontent.com/16778756/217568258-d6bc90aa-9eed-4e13-8f5b-add53e8c99aa.png">

**5)** Maybe this is more like a preference, but it would be nice if the multiple search results table could show p-value corrections like in the single search

_Multiple search_

<img width="903" alt="Screenshot 2023-02-08 at 15 09 00" src="https://user-images.githubusercontent.com/16778756/217569320-53b44949-7601-4904-8108-4e7b69f28770.png">

_Single search_

<img width="1178" alt="Screenshot 2023-02-08 at 15 11 08" src="https://user-images.githubusercontent.com/16778756/217569605-186f0978-a8b8-49c4-a99a-aa989a680a0e.png">
