### ISSUE TITLE
InterPro2GO/IBAs/Rfam2GO: summary of issue for external import

### ISSUE THREAD

**Issue by hattrill** [FlyBase/GO-curation#6]
This is a record of the issues that we have with the updating InterPro2GO pipeline and with implementing Rfam2go and improving IBA pipelines wrt making Protein2GO the source.

**Comment by hattrill** [comment]
Some issues:

- Non-Dmel species (current gene2go pipeline covers other species in FB)
- The logic for P2GO import does not allow annotations where one UniProtKB ID is mapped to multiple FBgns (ncRNA do not follow this rule)
- Also, where gene status is "not applicable" e.g. [His1](http://flybase.org/reports/FBgn0001195)
- Should the logic differ for Rfam2GO and InterPro2GO import vs ncRNA and prot coding genes?

**Comment by sjm41** [comment]
Just checking - we're recording issues with changing to direct import of InterPro2GO annotations from P2GO here? (rather than recording issues with the current pipeline?)

**Comment by hattrill** [comment]
Yes (this is mainly so I can document the reasoning behind the specs). But I am going to note some changes that I expect to see/issues that get fixed here (or at least a linked doc), as it's going to make life hard sorting out what gets fixed by new pipeline. But the file from GO is on their tracker and if I need to point HarvDev to a new InterPro2go file, I'll do that on JIRA and the specs for the devs will go on JIRA.....

**Comment by hattrill** [comment]
For completeness, link to issue about [stale InterPro2go file on GO site](https://github.com/geneontology/go-site/issues/1786)

**Comment by hattrill** [comment]
Currently
IEA pipeline: gene2go - gene-interpro ; interpro2go -> check if term associtated with gene:
if via IEA - if not, add or remove depending on Interpro2go file unless gene has manual annotation to term or child term, then do not add or remove IEA.

**Comment by hattrill** [comment]
Think that if we want to use manual NOTs as a basis for exclusion of IEAs, we should also do this for IBA.
Want:
Add all 'positive' IEAs, IBAs (never NOTs) regardless of manual annotation 
Except where there is a manual negative (NOT) annotation : I propose that this works as following:
1. where the manual NOT and IEA/IBA positive annotated term are the same, do not add the IEA/IBA
2. where the manual NOT is more specific, add the less specific positive IEA/IBA (as this could be true - a manual same/higher level term should be added to show at what level the gene product does not perform the function)
3. where the manual NOT is less specific, do not add the more specific IEA/IBA (as the parent NOT should propagate down the tree).  
<img width="1425" alt="NOT_logic" src="https://user-images.githubusercontent.com/11865746/153461941-95ac8164-de74-4082-949f-5cd529d5a723.png">

Adding handy fig to illustrate. Do you agree @sjm41 - with the logic not the handiness of the figure ;-)

**Comment by sjm41** [comment]
@hattrill I agree with your logic (and I also like the figure!).  But I'm wondering if this really needs to be done at the FB end? Do all other databases also have to write custom code to deal with NOTs, or do they just live with a mixture of positive/negative annotations.  Seems that the logic you describe could/should function at the P2GO (or Noctua) level, rather than each DB having to do it - or maybe that's what you're thinking??

WRT 'not applicable' genes, I think it would be absolutely fine for these to lack any GO annotation. In fact, this might be helpful as a user won't get them returned in GO searches (which is probably the desired outcome, as they can't do any experiments/analysis on 'not applicable' genes.)

**Comment by hattrill** [comment]
> @hattrill I agree with your logic (and I also like the figure!). But I'm wondering if this really needs to be done at the FB end? Do all other databases also have to write custom code to deal with NOTs, or do they just live with a mixture of positive/negative annotations. 

This has never been agreed on universally, despite many, many discussions. Ideally, this would work cross-the-board, but that is not a thing. 

Seems that the logic you describe could/should function at the P2GO (or Noctua) level, rather than each DB having to do it - or maybe that's what you're thinking?? 

Noctua - can't handle this complexity
P2GO: not sure if there is the bandwidth at the moment and whether UniProt would want this.
For our users, it makes sense - particularly with searches - but there is the agrument that there are not enough NOTs to warrent special coding. And, realistically, if we want it, we will have to do it.
I will give it more thought .....might just be my unwillingness to let go of what we have.

(And for IBA stuff, I thought the NOTs are meant to be handled correctly now within PAINT??)

Yes - I was thinking that too - would be nice not to have special rules here....perhaps I need a better system for making sure that these are spotted and fixed, as it seems to re-appear.
> 
> WRT 'not applicable' genes, I think it would be absolutely fine for these to lack any GO annotation. In fact, this might be helpful as a user won't get them returned in GO searches (which is probably the desired outcome, as they can't do any experiments/analysis on 'not applicable' genes.)

I am glad you think so - I was giving myself a headache with all the permutataions! Solved - ignore them!

**Comment by hattrill** [comment]
- Note: pipeline for InterPro2GO could go ahead without complex filtering if we can get an agreement on how to deal with IEAs across GOC - noting that there is a difference between groups display choices and GAF output. 

- Note: A survey cross GOC about InterPro2GO could be useful.

- [ ] Finish analysis of unfiltered InterPro2GO

**Comment by hattrill** [comment]
- [ ] Manual fix of InterPro issues in progress - not one single issue, so each must be reviewed in turn
- [ ] write new rules for adding NOTs to entities and propose to GOC
- [ ] make ticket for discontinuing InterPro pipeline and picking up annotations from P2GO as no blockers now

**Comment by hattrill** [comment]
One more thing to check: [multigene protein families](https://docs.google.com/spreadsheets/d/1vrZUsogZgQ4EfQCfskuicJ-sSNcZhIxl1jcvx7896eY/edit#gid=0) - do I need to have separate editting route for these?

**Comment by hattrill** [comment]
when there is no UniProtKB-FBgn mapping in file, we do not update the entry as this could have arisen due to mapping error rather than all annotations being removed. Manual check to make sure that annotations are removed are ok when dealing with the set we have, but adding IEAs to the mix is going to make things harder to police, I think. So need spec what should happen in the event that a FBgn with GO data has no data in GPAD from P2GO - no way to tell if this is because of the way the gpi is generated (using IDs from the GPAD) or whether there is no mapping.......

**Comment by hattrill** [comment]
Check example:
SM "Here’s just one example: I asked that glutathione oxidoreductase activity (GO:0097573) be added to IPR002109 in March 2021, and that got added to InterPro v85.0 (InterPro is now at v87.0):
P2GO annotations reflect this, e.g. for members of FBgg0001699:
Q9VJZ6, Q9W4S1, Q8SXQ5, Q9VNL4, Q9VVT6, Q9W2D1, Q9V420. (Though I can’t tell when P2GO started showing these….)
But these annotations to
GO:0097573 aren’t shown in FB"

grep'd IPR002109 from files from FB2022_02 release and this example looks fine:

From gene_association:
FB	FBgn0051559	CG31559	is_active_in	GO:0005575	FB:FBrf0159398|GO_REF:0000015	ND		C		31559|CG11461|CG15584	proteintaxon:7227	20080922	UniProt		
FB	FBgn0051559	CG31559	enables	GO:0097573	FB:FBrf0174215|GO_REF:0000002	IEA	InterPro:IPR002109	F		31559|CG11461|CG15584	protein	taxon:7227	20220311	InterPro		
[kochabpdncamacuk:GO/GAF_RELEASE/FB2022_02] hla28% grep IPR002109 gene_association.fb
FB	FBgn0029662	CG12206	enables	GO:0097573	FB:FBrf0174215|GO_REF:0000002	IEA	InterPro:IPR002109	F	protein	taxon:7227	20220311	InterPro		
FB	FBgn0030584	CG14407	enables	GO:0097573	FB:FBrf0174215|GO_REF:0000002	IEA	InterPro:IPR002109	F	BcDNA:RH03087|Grx5|Mitochondrial monothiol glutaredoxin-5	protein	taxon:7227	20220311	InterPro		
FB	FBgn0051559	CG31559	enables	GO:0097573	FB:FBrf0174215|GO_REF:0000002	IEA	InterPro:IPR002109	F	31559|CG11461|CG15584	protein	taxon:7227	20220311	InterPro		
FB	FBgn0032509	CG6523	enables	GO:0097573	FB:FBrf0174215|GO_REF:0000002	IEA	InterPro:IPR002109	F	Grx3|Grx4	protein	taxon:7227	20220311	InterPro		
FB	FBgn0036820	Grx1	enables	GO:0097573	FB:FBrf0174215|GO_REF:0000002	IEA	InterPro:IPR002109	F	Glutaredoxin 1	BcDNA:GH24739|CG6852	protein	taxon:7227	20220311	InterPro		
FB	FBgn0034658	Grx1t	enables	GO:0097573	FB:FBrf0174215|GO_REF:0000002	IEA	InterPro:IPR002109	F	Glutaredoxin 1, testis-specific	CG7975|Grx-1	protein	taxon:7227	20220311	InterPro		
FB	FBgn0004465	Su(P)	enables	GO:0097573	FB:FBrf0174215|GO_REF:0000002	IEA	InterPro:IPR002109	F	Suppressor of ref(2)P sterility	CG4086	protein	taxon:7227	20220311	InterPro	

From gene2go file:
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109
ADDED GO:0097573 - glutathione oxidoreductase activity due to InterPro:IPR002109

@sjm41 if there's anything you want to check, the files are attached.

**Comment by sjm41** [comment]
Thanks Helen. I just did several spot-checks on several delayed InterPro2GO annotations among the oxidoreductases, and they all look like they are fixed!  It will be easier for me to have a thorough check once the new web release is out, so I'll report any outstanding issues then.

**Comment by hattrill** [comment]
> * [x]  One more thing to check: [multigene protein families](https://docs.google.com/spreadsheets/d/1vrZUsogZgQ4EfQCfskuicJ-sSNcZhIxl1jcvx7896eY/edit#gid=0) - do I need to have separate editting route for these?

CHECKED and have fixed, examined so it is ok for one UniProt ID which maps to >1 FBgn to be propagated.
Would be good if annotations of member genes of an umbrella group were mapped to the parent group.

**Comment by hattrill** [comment]
- [ ] Check Not applicable gene model status genes
- [ ] Check unmapped genes
- [ ] Work out how to deal with pipeline so that genes that don't get updated are flagged

**Comment by hattrill** [comment]
GAF for non-Dmel species [nondmel_gaf.fb.gz](https://github.com/FlyBase/GO-curation/files/8343823/nondmel_gaf.fb.gz)

**Comment by sjm41** [comment]
Just confirming that the InterPro2GO annotations for enzymes in FB2022_02 have all been updated.  :-)

**Comment by hattrill** [comment]
- [x] Record for Rfam2GO mapping ha9010.bibl (assigned FBrf0253064)
- [x] Update https://github.com/geneontology/go-site/tree/master/metadata/gorefs#goref0000115 with FBrf mapping
- [x] Update details of InterPro2GO ref:
*U FBrf0174215
*T personal communication to FlyBase
*a FlyBase Curators
*b Swiss-Prot Project Members
*b InterPro Project Members
*t 2004-
*u Gene Ontology annotation in FlyBase through association of InterPro records with GO terms.
*L English
*G For annotations documented via this citation, GO terms were assigned to FlyBase genes through InterPro protein domain assignments. Interpro protein domains are assigned to FlyBase genes as part of an ongoing collaboration between the Swiss-Prot database and FlyBase. GO terms are then associated with FlyBase genes using a translation table of InterPro protein domains to GO terms generated by Nicola Mulder at the European Bioinformatics Institute.
The rationale for this set of annotations is to provide some GO annotation for genes that have few or no experimentally supported GO terms, albeit at relatively low-confidence. It is not designed to capture all possible InterPro-predicted GO terms. GO terms are selected for addition based on the following rules:
1. Where multiple InterPro domains predict the SAME GO statement, this GO term statement is included only once under any single gene.
2. Where an InterPro-predicted GO term is already associated with a gene and supported by non-IEA (Inferred from Electronic Annotation) evidence code, the InterPro-predicted GO term is not added. If the existing identical GO terms is supported by IEA, the Interpro predicted GO term is added.
3. Where a child of an InterPro-predicted GO term already exists for a gene, the InterPro-predicted GO term is not added. For example, &agr;-Est1 is already annotated with the GO term 'carboxylesterase activity ; GO:0004091 ; EC:3.1.1.1'.  This is a child of the InterPro-predicted GO term 'catalytic activity ; GO:0003824'.  Therefore 'catalytic activity ; GO:0003824' would NOT be added.

**Comment by hattrill** [comment]
Seems to be an issue with our NOT exclusion rules - if we move to getting IEAs from P2GO, not an issue.
For FBrf0227974 PTPases with NOT enables phosphatase activity (IDA/IKR) also getting enables protein tyrosine phosphatase activity (IEA) - check other examples.

**Comment by sjm41** [comment]
Here's 2 more examples:
FBgn0033673/CG8298 
FBgn0035392/CG1271 
Both have "NOT enables transferase activity" but are getting positive child terms from InterPro2GO.

**Comment by hattrill** [comment]
Not sure why this has happened - will get P2GO import route done by next release.

**Comment by hattrill** [comment]
Made pull request for Rfam FBrf -> GO-ref mapping pull/1915

**Comment by hattrill** [comment]
InterPro2GO annotations with old datestamp to be manually removed from chado in ha9116.edit.
[20221004_IEA.txt.gz](https://github.com/FlyBase/GO-curation/files/9876875/20221004_IEA.txt.gz)

**Comment by hattrill** [comment]
(note: fixed Rfam xref in external DBxrefs
DB1a Rfam
DBid 61
DB2a The Rfam database is a collection of RNA families, each represented by multiple sequence alignments, consensus secondary structures and covariance models (CMs).
DB3a https://rfam.org/
DB3b https://rfam.org/family/)
