### ISSUE TITLE
new piRNA terms 

### ISSUE THREAD

**Issue by gantonazzo** [FlyBase/GO-curation#7]
After various meetings within the miRNA working group, we now have the following terms:
- miRNA-mediated gene silencing
- siRNA-mediated gene silencing
- sRNA-mediated gene silencing

It would be good to have a "piRNA-mediated gene silencing" as well, and since they seem to have an important role in flies, it would make sense for us to request that term (and corresponding child terms).

This ticket is in place to collect info for this task, and discuss potential new terms and definitions.

Useful literature to start with:
PMID: 20080197, "piRNA-mediated silencing in Drosophila germlines", 2010 (https://pubmed.ncbi.nlm.nih.gov/20080197/)
PMID: 28964526, "piRNA Biogenesis in Drosophila Melanogaster", 2017 (https://pubmed.ncbi.nlm.nih.gov/28964526/)

**Comment by hattrill** [comment]
piRNA- and siRNA-mediated transcriptional repression in Drosophila, mice, and yeast: new insights and biodiversity. https://pubmed.ncbi.nlm.nih.gov/34347367/

**Comment by hattrill** [comment]
See https://github.com/FlyBase/GO-curation/issues/23
