### ISSUE TITLE
icon and video tut for pangea

### ISSUE THREAD

**Issue by hattrill** [FlyBase/GO-curation#71]
As per title

**Comment by gantonazzo** [comment]
First attempt at a logo:

![Screenshot 2023-03-17 at 17 30 06](https://user-images.githubusercontent.com/16778756/225976739-2e82dff5-bb57-40a9-87e4-3ea69ff7b191.png)

**Comment by hattrill** [comment]
You're a natural at this! I like it.

**Comment by hattrill** [comment]
Video tut done https://www.flyrnai.org/tools/pangea/web/about
